# file      : unit-tests/parser/buildfile
# copyright : Copyright (c) 2009-2013 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

#@@ Temporary until we get utility library support.
#
import libs = libcutl%lib{cutl}
src = lexer parser \
semantics/{class elements expression namespace option unit} \
traversal/{class elements namespace option unit}

exe{driver}: cxx{driver} ../../cli/cxx{$src} $libs test{testscript}

include ../../cli/
