# file      : unit-tests/parser/buildfile
# copyright : Copyright (c) 2009-2018 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

include ../../cli/
exe{driver}: {hxx cxx}{*} ../../cli/libue{cli} testscript
