# file      : tests/combined/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

exe{driver}: {hxx cxx}{* -test} cli.cxx{test} testscript

cxx.poptions =+ "-I$out_base"

cli.cxx{test}: cli{test}
cli.options = --generate-specifier --generate-file-scanner
