# file      : examples/hello/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

exe{driver}: {hxx cxx}{* -hello} cli.cxx{hello} doc{README}
exe{driver}: test.arguments = --greeting Hi John Jane

cxx.poptions =+ "-I$out_base"

cli.cxx{hello}: cli{hello}
