# file      : tests/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

d = ctor/ erase/ file/ headings/ inheritance/ specifier/ toc/
./: $d
include $d
