# file      : buildfile
# license   : MIT; see accompanying LICENSE file

./: {*/ -build/} doc{INSTALL NEWS README} legal{LICENSE} manifest

# Don't install the INSTALL file.
#
doc{INSTALL}@./: install = false
