# file      : buildfile
# license   : MIT; see accompanying LICENSE file

./: {*/ -build/} doc{INSTALL NEWS README} legal{LICENSE} manifest

# Don't install unit tests or the INSTALL file.
#
unit-tests/:     install = false
doc{INSTALL}@./: install = false
