# file      : tests/group/buildfile
# license   : MIT; see accompanying LICENSE file

exe{driver}: {hxx cxx}{* -test} cli.cxx{test} testscript

cxx.poptions =+ "-I$out_base"

cli.cxx{test}: cli{test}
cli.options = --generate-group-scanner
