# file      : tests/specifier/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

exe{driver}: {hxx cxx}{* -test} cli.cxx{test}
exe{driver}: test.arguments = -a -c foo

cxx.poptions =+ "-I$out_base"

cli.cxx{test}: cli{test}
cli.options = --generate-specifier --generate-modifier
