# file      : examples/features/buildfile
# copyright : Copyright (c) 2009-2013 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{driver} {hxx ixx cxx}{options} doc{README}

cxx.poptions =+ -I$out_base

# Generated options parser.
#
{hxx ixx cxx}{options}: cli{options}
