# file      : tests/ctor/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{driver} cli.cxx{test}

cxx.poptions =+ "-I$out_base"

cli.cxx{test}: cli{test}
