# file      : tests/ctor/buildfile
# copyright : Copyright (c) 2009-2019 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

exe{driver}: {hxx cxx}{* -test} cli.cxx{test}

cxx.poptions =+ "-I$out_base"

cli.cxx{test}: cli{test}
