# file      : tests/file/buildfile
# copyright : Copyright (c) 2009-2017 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

exe{driver}: cxx{driver} {hxx ixx cxx}{test} test{testscript}

cxx.poptions =+ "-I$out_base"

# Generated options parser.
#
{hxx ixx cxx}{test}: cli{test}

cli.options = --generate-file-scanner
