# file      : unit-tests/lexer/buildfile
# copyright : Copyright (c) 2009-2018 Code Synthesis Tools CC
# license   : MIT; see accompanying LICENSE file

include ../../cli/
exe{driver}: {hxx cxx}{*} ../../cli/libu{cli} testscript
